# Generated by Django 2.1.4 on 2019-01-06 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assigned', models.DateTimeField()),
                ('date_consumed', models.DateTimeField(default=None, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doses', to='recipes.Recipe')),
            ],
        ),
    ]
