# Generated by Django 2.1.4 on 2019-01-15 19:29

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_dose'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_measured', models.DateTimeField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=6)),
                ('relative_humidity', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='dose',
            name='date_consumed',
        ),
        migrations.AddField(
            model_name='dose',
            name='is_consumed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='max_relative_humidity',
            field=models.DecimalField(decimal_places=2, default=Decimal('65.0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='recipe',
            name='max_temperature',
            field=models.DecimalField(decimal_places=2, default=Decimal('25.0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='recipe',
            name='min_relative_humidity',
            field=models.DecimalField(decimal_places=2, default=Decimal('55.0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='recipe',
            name='min_temperature',
            field=models.DecimalField(decimal_places=2, default=Decimal('-10.0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='measure',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='recipes.Recipe'),
        ),
    ]
